<?php

/**
 * Realistic FSEG + FSI payloads for scripts/seed-ub-faculty-content.php
 * Sources: fseg.ub.edu.bi, fsi.ub.edu.bi, ub.edu.bi
 *
 * @return array<string, array<string, mixed>>
 */
return [
    'fseg' => [
        'meta' => [
            'email' => 'decanatfseg@ub.edu.bi',
            'phone' => '(+257) 22 22 67 75',
            'address' => 'Faculté des Sciences Économiques et de Gestion, Université du Burundi, Bujumbura',
            'primary' => '#0D9B49',
            'secondary' => '#0B6F38',
        ],
        'home' => [
            'hero_badge' => 'FSEG — Université du Burundi',
            'hero_title' => 'Économie et gestion au service du développement',
            'hero_text' => 'La Faculté des Sciences Économiques et de Gestion forme des économistes et gestionnaires capables d’analyser les politiques publiques, de piloter les organisations et d’accompagner le développement rural et urbain du Burundi.',
            'hero_primary_label' => 'Découvrir les formations',
            'hero_primary_url' => '/formations',
            'hero_secondary_label' => 'Contacter la faculté',
            'hero_secondary_url' => '/contact',
            'hero_media_type' => 'image',
            'hero_media_path' => 'assets/images/faculties/fseg/hero-1.jpg',
            'about_label' => 'Présentation',
            'about_title' => 'Trois départements pour l’économie et la gestion',
            'about_body' => "La FSEG regroupe les départements de Gestion, d’Économie politique et d’Économie rurale.\n\nSous la direction du doyen Pr. Willy Marcel Ndayitwayeko, la faculté combine enseignement, recherche et ouverture sur les institutions publiques et le secteur privé.",
            'about_button_label' => 'En savoir plus',
            'about_button_url' => '/faculte',
            'research_label' => 'Recherche',
            'research_title' => 'Politiques économiques et développement',
            'research_body' => 'Les travaux portent sur l’économie du développement, la gouvernance des organisations, l’économie rurale et les dynamiques de marché en Afrique des Grands Lacs.',
            'research_button_label' => 'Explorer la recherche',
            'research_button_url' => '/recherche',
            'programmes_label' => 'Formations',
            'programmes_title' => 'Licences et masters en économie et gestion',
            'programmes_text' => 'Parcours en gestion, économie politique et économie rurale, du baccalauréat au master.',
            'programmes_button_label' => 'Voir les formations',
            'programmes_button_url' => '/formations',
            'posts_label' => 'Actualités',
            'posts_title' => 'Vie de la FSEG',
            'posts_text' => 'Annonces académiques, séminaires et événements de la faculté.',
            'posts_button_label' => 'Voir tout',
            'posts_button_url' => '/actualites',
            'seo_title' => 'FSEG | Université du Burundi',
            'seo_description' => 'Faculté des Sciences Économiques et de Gestion de l’Université du Burundi.',
        ],
        'home_en' => [
            'hero_title' => 'Economics and management for development',
            'hero_text' => 'The Faculty of Economics and Management trains economists and managers for public policy, organizations and rural development in Burundi.',
            'about_title' => 'Three departments in economics and management',
            'about_body' => 'FSEG brings together Management, Political Economy and Rural Economics under Dean Prof. Willy Marcel Ndayitwayeko.',
            'seo_title' => 'FSEG | University of Burundi',
            'seo_description' => 'Faculty of Economics and Management at the University of Burundi.',
        ],
        'settings' => [
            ['institution.faculty_name', 'Faculté des Sciences Économiques et de Gestion', 'string', 'institution'],
            ['institution.short_name', 'FSEG', 'string', 'institution'],
            ['institution.university', 'Université du Burundi', 'string', 'institution'],
            ['contact.address', 'Université du Burundi — FSEG, Bujumbura', 'string', 'contact'],
            ['contact.phone', '(+257) 22 22 67 75', 'string', 'contact'],
            ['contact.email', 'decanatfseg@ub.edu.bi', 'email', 'contact'],
            ['contact.hours', 'Lundi–Vendredi, 8h00–16h00', 'string', 'contact'],
            ['footer.text', 'FSEG — Université du Burundi. Économie, gestion et développement.', 'text', 'footer'],
            ['footer.copyright', '© ' . date('Y') . ' FSEG — Université du Burundi', 'string', 'footer'],
            ['seo.default_title', 'FSEG | Université du Burundi', 'string', 'seo'],
            ['seo.default_description', 'Faculté des Sciences Économiques et de Gestion de l’Université du Burundi.', 'text', 'seo'],
            ['seo.theme_color', '#0D9B49', 'color', 'seo'],
        ],
        'stats' => [
            ['home_main', 'Étudiants FSEG', 2800, '+', 1],
            ['home_main', 'Départements', 3, '', 2],
            ['home_main', 'Enseignants', 60, '+', 3],
            ['home_research', 'Publications / an', 25, '+', 1],
            ['home_research', 'Projets', 8, '', 2],
            ['alumni', 'Diplômés', 9000, '+', 1],
        ],
        'programmes' => [
            [
                'level' => 'licence',
                'title' => 'Licence en Gestion',
                'slug' => 'licence-gestion',
                'duration' => '3 ans (LMD)',
                'summary' => 'Formation en management, comptabilité, marketing et administration des organisations (département de Gestion).',
                'description' => 'La licence en Gestion prépare aux métiers de l’entreprise et de l’administration. Elle s’appuie sur le département de Gestion dirigé par le PA Rédempteur Ntawiratsa.',
                'admission_conditions' => 'Certificat d’Humanités (section sciences économiques ou équivalent) ; modalités UB.',
                'career_outcomes' => json_encode(['Gestionnaire', 'Comptable junior', 'Assistant marketing', 'Administration publique'], JSON_UNESCAPED_UNICODE),
                'display_order' => 1,
                'featured_on_home' => 1,
                'home_order' => 1,
                'is_published' => 1,
            ],
            [
                'level' => 'licence',
                'title' => 'Licence en Économie politique',
                'slug' => 'licence-economie-politique',
                'duration' => '3 ans (LMD)',
                'summary' => 'Analyse économique, politiques publiques et macroéconomie (département d’Économie politique).',
                'description' => 'Ce parcours forme à l’analyse des politiques économiques et des institutions. Département d’Économie politique — PA Léonidas Ndayizeye.',
                'admission_conditions' => 'Certificat d’Humanités ou équivalent ; modalités UB.',
                'career_outcomes' => json_encode(['Analyste économique', 'Administration', 'Banque / finance', 'Recherche'], JSON_UNESCAPED_UNICODE),
                'display_order' => 2,
                'featured_on_home' => 1,
                'home_order' => 2,
                'is_published' => 1,
            ],
            [
                'level' => 'master',
                'title' => 'Master en Économie rurale et développement',
                'slug' => 'master-economie-rurale',
                'duration' => '2 ans',
                'summary' => 'Économie rurale, filières agricoles et développement territorial (département d’Économie rurale).',
                'description' => 'Le master approfondit l’économie rurale et le développement. Le département est dirigé par le doyen Pr. Willy Marcel Ndayitwayeko.',
                'admission_conditions' => 'Licence en économie, agronomie économique ou apparentée ; sélection FSEG.',
                'career_outcomes' => json_encode(['Expert développement rural', 'Projets / ONG', 'Ministères', 'Recherche'], JSON_UNESCAPED_UNICODE),
                'display_order' => 3,
                'featured_on_home' => 1,
                'home_order' => 3,
                'is_published' => 1,
            ],
        ],
        'staff' => [
            [
                'category' => 'enseignant',
                'name' => 'Pr. Willy Marcel Ndayitwayeko',
                'slug' => 'willy-marcel-ndayitwayeko',
                'grade' => 'Doyen',
                'specialty' => 'Économie rurale',
                'role' => 'Doyen de la FSEG',
                'email' => 'decanatfseg@ub.edu.bi',
                'biography' => 'Doyen de la Faculté des Sciences Économiques et de Gestion ; également responsable du département d’Économie rurale (fseg.ub.edu.bi).',
                'display_order' => 1,
                'is_published' => 1,
                'photo' => null,
            ],
            [
                'category' => 'enseignant',
                'name' => 'Dr. Salomon Nsabimana',
                'slug' => 'salomon-nsabimana',
                'grade' => 'Vice-doyen',
                'specialty' => 'Économie et gestion',
                'role' => 'Vice-doyen',
                'email' => 'decanatfseg@ub.edu.bi',
                'biography' => 'Vice-doyen de la FSEG selon l’administration officielle de la faculté.',
                'display_order' => 2,
                'is_published' => 1,
                'photo' => null,
            ],
        ],
        'labs' => [[
            'abbreviation' => 'CER-FSEG',
            'name' => 'Cellule d’études économiques et de gestion',
            'slug' => 'cellule-etudes-economiques',
            'icon' => 'bi-graph-up',
            'description' => 'Espace de recherche sur les politiques économiques, la gouvernance des organisations et l’économie rurale.',
            'themes' => json_encode(['Politiques publiques', 'Gestion des organisations', 'Économie rurale'], JSON_UNESCAPED_UNICODE),
            'researcher_count' => 18,
            'display_order' => 1,
            'featured_on_home' => 1,
            'home_order' => 1,
            'is_published' => 1,
        ]],
        'publications' => [[
            'year' => (int) date('Y'),
            'title' => 'Travaux de la FSEG sur l’économie et le développement au Burundi',
            'authors' => 'Enseignants-chercheurs de la FSEG',
            'journal' => 'Université du Burundi',
            'url' => null,
            'display_order' => 1,
            'is_published' => 1,
        ]],
        'projects' => [[
            'code' => 'FSEG-DEV',
            'title' => 'Économie du développement et gouvernance',
            'description' => 'Projet structurant d’appui à la recherche et à la formation en économie et gestion.',
            'funder' => 'Université du Burundi / partenaires',
            'period_start' => 2022,
            'period_end' => null,
            'icon' => 'bi-briefcase',
            'display_order' => 1,
            'is_published' => 1,
        ]],
        'timeline' => [
            ['year' => 1963, 'title' => 'Ouverture de l’Économie', 'description' => 'Ouverture de facultés de Philosophie, Lettres et Économie au collège du Saint-Esprit à Bujumbura.', 'display_order' => 1, 'is_published' => 1],
            ['year' => 1964, 'title' => 'Intégration universitaire', 'description' => 'Intégration à l’Université officielle de Bujumbura, devenue Université du Burundi.', 'display_order' => 2, 'is_published' => 1],
            ['year' => 2024, 'title' => 'FSEG contemporaine', 'description' => 'Trois départements actifs : Gestion, Économie politique, Économie rurale.', 'display_order' => 3, 'is_published' => 1],
        ],
        'alumni' => [
            'profile' => [
                'name' => 'Alumni FSEG',
                'slug' => 'alumni-fseg',
                'photo' => null,
                'promotion' => 'Promotion type',
                'role' => 'Cadre économique',
                'organization' => 'Secteur public / privé',
                'biography' => 'Exemple de parcours d’un lauréat de la FSEG.',
                'display_order' => 1,
                'is_published' => 1,
            ],
            'testimonial' => [
                'person_name' => 'Ancien·ne de la FSEG',
                'photo' => null,
                'promotion' => 'Gestion / Économie',
                'quote' => 'La FSEG m’a donné des outils d’analyse économique et de management directement utiles sur le terrain.',
                'display_order' => 1,
                'is_published' => 1,
            ],
        ],
        'posts' => [
            [
                'type' => 'news',
                'title' => 'Rentrée académique à la FSEG',
                'slug' => 'rentree-fseg',
                'excerpt' => 'Ouverture de l’année académique pour les étudiants en économie et gestion.',
                'body' => 'La Faculté des Sciences Économiques et de Gestion accueille les nouvelles promotions. Contact décanat : (+257) 22 22 67 75 — decanatfseg@ub.edu.bi.',
                'status' => 'published',
                'published_at' => date('Y-m-d H:i:s'),
                'featured' => 1,
                'home_order' => 1,
                'event_starts_at' => null,
                'event_ends_at' => null,
                'event_location' => null,
                'registration_url' => null,
                'seo_title' => 'Rentrée FSEG',
                'seo_description' => 'Rentrée académique de la FSEG.',
                'cover_image' => null,
                'created_by' => null,
                'updated_by' => null,
            ],
            [
                'type' => 'event',
                'title' => 'Séminaire d’économie du développement',
                'slug' => 'seminaire-economie-developpement',
                'excerpt' => 'Séminaire ouvert organisé par les départements d’économie.',
                'body' => 'Enseignants et étudiants débattent des enjeux de développement économique du Burundi.',
                'status' => 'published',
                'published_at' => date('Y-m-d H:i:s'),
                'featured' => 1,
                'home_order' => 2,
                'event_starts_at' => date('Y-m-d 09:00:00', strtotime('+40 days')),
                'event_ends_at' => date('Y-m-d 12:00:00', strtotime('+40 days')),
                'event_location' => 'FSEG — Campus UB, Bujumbura',
                'registration_url' => null,
                'seo_title' => 'Séminaire FSEG',
                'seo_description' => 'Séminaire d’économie du développement.',
                'cover_image' => null,
                'created_by' => null,
                'updated_by' => null,
            ],
        ],
        'highlights' => [
            ['bi-building', 'Trois départements', 'Gestion, Économie politique et Économie rurale.', 1],
            ['bi-graph-up-arrow', 'Formation professionnalisante', 'Parcours orientés emploi public, privé et développement.', 2],
            ['bi-people', 'Réseau alumni', 'Cadres économiques et gestionnaires formés à l’UB.', 3],
        ],
        'pages' => [
            'faculty' => [
                'title' => 'La Faculté',
                'content' => [
                    'banner_subtitle' => 'FSEG — Sciences économiques et de gestion',
                    'banner_image' => 'assets/images/faculties/fseg/banner.jpg',
                    'dean' => [
                        'label' => 'Mot du doyen',
                        'title' => 'Former pour le développement',
                        'photo' => '',
                        'name' => 'Pr. Willy Marcel Ndayitwayeko',
                        'role' => 'Doyen',
                        'specialty' => 'Économie rurale',
                        'signature' => 'Pr. Willy Marcel Ndayitwayeko',
                        'paragraphs' => [
                            'La FSEG forme des économistes et gestionnaires engagés au service du Burundi.',
                            'Nos trois départements — Gestion, Économie politique et Économie rurale — travaillent main dans la main avec les institutions et le monde professionnel.',
                        ],
                    ],
                    'mission_label' => 'Mission et vision',
                    'mission_title' => 'Excellence en économie et gestion',
                    'mission' => ['icon' => 'bi-bullseye', 'title' => 'Mission', 'paragraphs' => ['Former des cadres capables d’analyser et de piloter l’économie et les organisations.']],
                    'vision' => ['icon' => 'bi-eye', 'title' => 'Vision', 'paragraphs' => ['Une faculté de référence en économie et gestion dans la sous-région.']],
                    'values' => [
                        ['icon' => 'bi-bar-chart', 'title' => 'Rigueur', 'description' => 'Analyse fondée sur les données et la théorie.'],
                        ['icon' => 'bi-people', 'title' => 'Service', 'description' => 'Ouverture sur les besoins de la société.'],
                        ['icon' => 'bi-lightbulb', 'title' => 'Innovation', 'description' => 'Approches pédagogiques et recherche appliquée.'],
                    ],
                    'history' => [
                        'label' => 'Historique',
                        'title' => 'De l’Économie de 1963 à la FSEG',
                        'text' => 'Héritière des enseignements d’économie ouverts en 1963, la FSEG est aujourd’hui structurée en trois départements complémentaires.',
                    ],
                ],
                'seo_title' => 'La FSEG | Université du Burundi',
                'seo_description' => 'Présentation de la FSEG.',
            ],
            'formations' => [
                'title' => 'Formations',
                'content' => [
                    'banner_subtitle' => 'Gestion, économie politique, économie rurale',
                    'banner_image' => 'assets/images/faculties/fseg/banner.jpg',
                    'offer_label' => 'Offre académique',
                    'offer_title' => 'Programmes FSEG',
                    'offer_text' => 'Licences et masters dans les trois départements de la faculté.',
                    'cta_title' => 'Informations d’inscription',
                    'cta_text' => 'Contactez le décanat au (+257) 22 22 67 75.',
                    'cta_label' => 'Contacter la faculté',
                    'cta_url' => '/contact',
                ],
                'seo_title' => 'Formations — FSEG',
                'seo_description' => 'Programmes de la FSEG.',
            ],
            'research' => [
                'title' => 'Recherche',
                'content' => [
                    'banner_subtitle' => 'Recherche en économie et gestion',
                    'banner_image' => 'assets/images/faculties/fseg/banner.jpg',
                    'labs_label' => 'Équipes',
                    'labs_title' => 'Cellules de recherche',
                    'labs_text' => 'Les départements structurent la recherche en économie et gestion.',
                    'publications_label' => 'Publications',
                    'publications_title' => 'Travaux récents',
                    'publications_text' => 'Articles, rapports et mémoires issus de la FSEG.',
                    'projects_label' => 'Projets',
                    'projects_title' => 'Projets structurants',
                ],
                'seo_title' => 'Recherche — FSEG',
                'seo_description' => 'Recherche à la FSEG.',
            ],
            'alumni' => [
                'title' => 'Alumni',
                'content' => [
                    'banner_subtitle' => 'Réseau des diplômés FSEG',
                    'banner_image' => 'assets/images/faculties/fseg/banner.jpg',
                    'intro_label' => 'Communauté',
                    'intro_title' => 'Anciens de la FSEG',
                    'intro_paragraphs' => ['Les diplômés évoluent dans l’administration, la banque, les entreprises et les projets de développement.'],
                    'profiles_label' => 'Profils',
                    'profiles_title' => 'Parcours alumni',
                    'profiles_text' => 'Exemples de trajectoires.',
                    'testimonials_label' => 'Témoignages',
                    'testimonials_title' => 'Ils témoignent',
                    'cta_title' => 'Rejoindre le réseau',
                    'cta_text' => 'Contactez le décanat pour actualiser votre profil.',
                    'cta_label' => 'Nous contacter',
                    'cta_url' => '/contact',
                ],
                'seo_title' => 'Alumni — FSEG',
                'seo_description' => 'Alumni FSEG.',
            ],
            'contact' => [
                'title' => 'Contact',
                'content' => [
                    'banner_subtitle' => 'FSEG — Campus Mutanga, Université du Burundi',
                    'banner_image' => 'assets/images/faculties/fseg/banner.jpg',
                    'contact_label' => 'Coordonnées',
                    'contact_title' => 'Contacter la FSEG',
                    'form_title' => 'Envoyer un message',
                    'form_help' => 'Indiquez le département concerné (Gestion, Économie politique, Économie rurale) si possible.',
                    'map_url' => 'https://www.google.com/maps?q=-3.376061%2C29.383330%20(FSEG%20%E2%80%94%20Campus%20Mutanga%2C%20Universit%C3%A9%20du%20Burundi)&hl=fr&z=17&output=embed',
                ],
                'seo_title' => 'Contact — FSEG',
                'seo_description' => 'Contacter la FSEG.',
            ],
        ],
        'dean_block' => 'Message du doyen Pr. Willy Marcel Ndayitwayeko : former des économistes et gestionnaires au service du développement du Burundi.',
    ],

    'fsi' => [
        'meta' => [
            'email' => 'fsi-info@ub.edu.bi',
            'phone' => '(+257) 22 22 47 94 / 22 22 48 82',
            'address' => '164, Chaussée Prince Louis Rwagasore, Campus Kiriri, B.P. 2700, Bujumbura, Burundi',
            'primary' => '#1565C0',
            'secondary' => '#0D47A1',
        ],
        'home' => [
            'hero_badge' => 'FSI — Université du Burundi',
            'hero_title' => 'Former les ingénieurs de demain',
            'hero_text' => 'La Faculté des Sciences de l’Ingénieur prépare des ingénieurs en génie civil, architecture et urbanisme, électromécanique et technologies de l’information, sur le campus Kiriri à Bujumbura.',
            'hero_primary_label' => 'Découvrir les formations',
            'hero_primary_url' => '/formations',
            'hero_secondary_label' => 'Contacter la faculté',
            'hero_secondary_url' => '/contact',
            'hero_media_type' => 'image',
            'hero_media_path' => 'assets/images/faculties/fsi/hero-1.jpg',
            'about_label' => 'Présentation',
            'about_title' => 'Quatre départements d’ingénierie',
            'about_body' => "Née de la fusion de la Faculté des Sciences Appliquées et de l’Institut Technique Supérieur, la FSI regroupe le Génie civil et environnemental, l’Architecture et l’urbanisme, l’Électromécanique et les TIC.\n\nDirection : doyen Dr-Ir Abraham Niyongere ; vice-doyen Dr Josias Bizindavyi.",
            'about_button_label' => 'En savoir plus',
            'about_button_url' => '/faculte',
            'research_label' => 'Recherche',
            'research_title' => 'Ingénierie et innovation',
            'research_body' => 'Projets en infrastructures, énergie, numérique et aménagement urbain, en lien avec les besoins nationaux.',
            'research_button_label' => 'Explorer la recherche',
            'research_button_url' => '/recherche',
            'programmes_label' => 'Formations',
            'programmes_title' => 'Filières d’ingénieur',
            'programmes_text' => 'Parcours en génie civil, architecture, électromécanique et TIC.',
            'programmes_button_label' => 'Voir les formations',
            'programmes_button_url' => '/formations',
            'posts_label' => 'Actualités',
            'posts_title' => 'Vie de la FSI',
            'posts_text' => 'Annonces pédagogiques, projets étudiants et événements du campus Kiriri.',
            'posts_button_label' => 'Voir tout',
            'posts_button_url' => '/actualites',
            'seo_title' => 'FSI | Université du Burundi',
            'seo_description' => 'Faculté des Sciences de l’Ingénieur — Campus Kiriri, Bujumbura.',
        ],
        'home_en' => [
            'hero_title' => 'Training tomorrow’s engineers',
            'hero_text' => 'The Faculty of Engineering Sciences trains engineers in civil engineering, architecture & urban planning, electromechanics and ICT at Kiriri campus.',
            'about_title' => 'Four engineering departments',
            'about_body' => 'FSI covers Civil & Environmental Engineering, Architecture & Urban Planning, Electromechanics and ICT, led by Dean Dr-Ir Abraham Niyongere.',
            'seo_title' => 'FSI | University of Burundi',
            'seo_description' => 'Faculty of Engineering Sciences at the University of Burundi.',
        ],
        'settings' => [
            ['institution.faculty_name', 'Faculté des Sciences et Ingénierie', 'string', 'institution'],
            ['institution.short_name', 'FSI', 'string', 'institution'],
            ['institution.university', 'Université du Burundi', 'string', 'institution'],
            ['contact.address', '164, Chaussée Prince Louis Rwagasore, Campus Kiriri, B.P. 2700 Bujumbura', 'string', 'contact'],
            ['contact.phone', '(+257) 22 22 47 94 / 22 22 48 82', 'string', 'contact'],
            ['contact.email', 'fsi-info@ub.edu.bi', 'email', 'contact'],
            ['contact.hours', 'Lundi–Vendredi, 8h00–16h00', 'string', 'contact'],
            ['footer.text', 'FSI — Université du Burundi. Ingénierie, architecture et technologies.', 'text', 'footer'],
            ['footer.copyright', '© ' . date('Y') . ' FSI — Université du Burundi', 'string', 'footer'],
            ['seo.default_title', 'FSI | Université du Burundi', 'string', 'seo'],
            ['seo.default_description', 'Faculté des Sciences de l’Ingénieur, Campus Kiriri.', 'text', 'seo'],
            ['seo.theme_color', '#1565C0', 'color', 'seo'],
        ],
        'stats' => [
            ['home_main', 'Étudiants FSI', 1500, '+', 1],
            ['home_main', 'Départements', 4, '', 2],
            ['home_main', 'Enseignants', 55, '+', 3],
            ['home_research', 'Projets techniques', 15, '+', 1],
            ['home_research', 'Laboratoires', 6, '', 2],
            ['alumni', 'Ingénieurs formés', 5000, '+', 1],
        ],
        'programmes' => [
            [
                'level' => 'licence',
                'title' => 'Licence en Génie civil et environnemental',
                'slug' => 'licence-genie-civil',
                'duration' => '3 ans (LMD)',
                'summary' => 'Structures, matériaux, hydraulique et environnement (département Génie civil et environnemental).',
                'description' => 'Formation d’ingénieurs civils pour les infrastructures et l’environnement. Département dirigé par le Dr-Ir Paul Nibasumba.',
                'admission_conditions' => 'Certificat d’Humanités scientifiques ; modalités UB.',
                'career_outcomes' => json_encode(['Ingénieur civil', 'BTP', 'Hydraulique', 'Environnement'], JSON_UNESCAPED_UNICODE),
                'display_order' => 1,
                'featured_on_home' => 1,
                'home_order' => 1,
                'is_published' => 1,
            ],
            [
                'level' => 'licence',
                'title' => 'Licence en Architecture et urbanisme',
                'slug' => 'licence-architecture-urbanisme',
                'duration' => '3 ans (LMD)',
                'summary' => 'Conception architecturale et aménagement urbain (département d’Architecture et d’Urbanisme).',
                'description' => 'Parcours orienté conception et planification urbaine. Département — MSc Channel Sibomana.',
                'admission_conditions' => 'Certificat d’Humanités ; modalités UB.',
                'career_outcomes' => json_encode(['Architecte junior', 'Urbaniste', 'Agences de conception', 'Collectivités'], JSON_UNESCAPED_UNICODE),
                'display_order' => 2,
                'featured_on_home' => 1,
                'home_order' => 2,
                'is_published' => 1,
            ],
            [
                'level' => 'licence',
                'title' => 'Licence en Électromécanique',
                'slug' => 'licence-electromecanique',
                'duration' => '3 ans (LMD)',
                'summary' => 'Électricité, mécanique et systèmes industriels (département d’Électromécanique).',
                'description' => 'Formation aux systèmes électromécaniques. Département — MSc Léonidas Ndayiragije.',
                'admission_conditions' => 'Certificat d’Humanités scientifiques ; modalités UB.',
                'career_outcomes' => json_encode(['Technicien supérieur', 'Maintenance industrielle', 'Énergie', 'Industrie'], JSON_UNESCAPED_UNICODE),
                'display_order' => 3,
                'featured_on_home' => 1,
                'home_order' => 3,
                'is_published' => 1,
            ],
            [
                'level' => 'licence',
                'title' => 'Licence en Technologies de l’information et de la communication',
                'slug' => 'licence-tic',
                'duration' => '3 ans (LMD)',
                'summary' => 'Informatique, réseaux et systèmes d’information (département TIC).',
                'description' => 'Parcours numérique et systèmes d’information. Département — Dr Ir Hassan Kibeya.',
                'admission_conditions' => 'Certificat d’Humanités scientifiques ; modalités UB.',
                'career_outcomes' => json_encode(['Développeur', 'Administrateur systèmes', 'Réseaux', 'Services numériques'], JSON_UNESCAPED_UNICODE),
                'display_order' => 4,
                'featured_on_home' => 0,
                'home_order' => null,
                'is_published' => 1,
            ],
        ],
        'staff' => [
            [
                'category' => 'enseignant',
                'name' => 'Dr-Ir Abraham Niyongere',
                'slug' => 'abraham-niyongere',
                'grade' => 'Doyen',
                'specialty' => 'Sciences de l’ingénieur',
                'role' => 'Doyen de la FSI',
                'email' => 'fsi-decanat@ub.edu.bi',
                'biography' => 'Doyen de la Faculté des Sciences de l’Ingénieur (fsi.ub.edu.bi).',
                'display_order' => 1,
                'is_published' => 1,
                'photo' => null,
            ],
            [
                'category' => 'enseignant',
                'name' => 'Dr Josias Bizindavyi',
                'slug' => 'josias-bizindavyi',
                'grade' => 'Vice-doyen',
                'specialty' => 'Sciences de l’ingénieur',
                'role' => 'Vice-doyen',
                'email' => 'fsi-info@ub.edu.bi',
                'biography' => 'Vice-doyen de la FSI.',
                'display_order' => 2,
                'is_published' => 1,
                'photo' => null,
            ],
        ],
        'labs' => [[
            'abbreviation' => 'LAB-FSI',
            'name' => 'Plateforme technique FSI',
            'slug' => 'plateforme-technique-fsi',
            'icon' => 'bi-gear',
            'description' => 'Espaces de travaux pratiques en génie civil, électromécanique et TIC sur le campus Kiriri.',
            'themes' => json_encode(['Infrastructures', 'Énergie', 'Numérique', 'Urbanisme'], JSON_UNESCAPED_UNICODE),
            'researcher_count' => 22,
            'display_order' => 1,
            'featured_on_home' => 1,
            'home_order' => 1,
            'is_published' => 1,
        ]],
        'publications' => [[
            'year' => (int) date('Y'),
            'title' => 'Projets et mémoires d’ingénierie de la FSI',
            'authors' => 'Enseignants et étudiants de la FSI',
            'journal' => 'Université du Burundi',
            'url' => null,
            'display_order' => 1,
            'is_published' => 1,
        ]],
        'projects' => [[
            'code' => 'FSI-INFRA',
            'title' => 'Ingénierie pour les infrastructures nationales',
            'description' => 'Appui à la formation pratique et aux projets étudiants en génie civil et énergies.',
            'funder' => 'Université du Burundi / partenaires',
            'period_start' => 2021,
            'period_end' => null,
            'icon' => 'bi-building',
            'display_order' => 1,
            'is_published' => 1,
        ]],
        'timeline' => [
            ['year' => 2011, 'title' => 'Fusion FSA / ITS', 'description' => 'La FSI résulte de la fusion de la Faculté des Sciences Appliquées et de l’Institut Technique Supérieur dans le cadre du LMD.', 'display_order' => 1, 'is_published' => 1],
            ['year' => 2020, 'title' => 'Quatre départements', 'description' => 'Organisation en Génie civil, Architecture & urbanisme, Électromécanique et TIC.', 'display_order' => 2, 'is_published' => 1],
            ['year' => 2024, 'title' => 'Campus Kiriri', 'description' => 'Poursuite des formations sur le campus Kiriri, Chaussée Prince Louis Rwagasore.', 'display_order' => 3, 'is_published' => 1],
        ],
        'alumni' => [
            'profile' => [
                'name' => 'Alumni FSI',
                'slug' => 'alumni-fsi',
                'photo' => null,
                'promotion' => 'Promotion type',
                'role' => 'Ingénieur',
                'organization' => 'BTP / énergie / numérique',
                'biography' => 'Exemple de parcours d’un ingénieur formé à la FSI.',
                'display_order' => 1,
                'is_published' => 1,
            ],
            'testimonial' => [
                'person_name' => 'Ancien·ne de la FSI',
                'photo' => null,
                'promotion' => 'Génie civil',
                'quote' => 'Les projets pratiques du campus Kiriri m’ont préparé·e aux chantiers et aux bureaux d’études.',
                'display_order' => 1,
                'is_published' => 1,
            ],
        ],
        'posts' => [
            [
                'type' => 'news',
                'title' => 'Rentrée à la Faculté des Sciences de l’Ingénieur',
                'slug' => 'rentree-fsi',
                'excerpt' => 'Accueil des étudiants sur le campus Kiriri.',
                'body' => 'La FSI ouvre l’année académique. Contacts : (+257) 22 22 47 94 / 22 22 48 82 — fsi-info@ub.edu.bi.',
                'status' => 'published',
                'published_at' => date('Y-m-d H:i:s'),
                'featured' => 1,
                'home_order' => 1,
                'event_starts_at' => null,
                'event_ends_at' => null,
                'event_location' => null,
                'registration_url' => null,
                'seo_title' => 'Rentrée FSI',
                'seo_description' => 'Rentrée académique de la FSI.',
                'cover_image' => null,
                'created_by' => null,
                'updated_by' => null,
            ],
            [
                'type' => 'event',
                'title' => 'Journée projets ingénieurs',
                'slug' => 'journee-projets-ingenieurs',
                'excerpt' => 'Présentation des projets étudiants des quatre départements.',
                'body' => 'Les départements de la FSI exposent les travaux pratiques et projets de fin d’études.',
                'status' => 'published',
                'published_at' => date('Y-m-d H:i:s'),
                'featured' => 1,
                'home_order' => 2,
                'event_starts_at' => date('Y-m-d 09:00:00', strtotime('+50 days')),
                'event_ends_at' => date('Y-m-d 16:00:00', strtotime('+50 days')),
                'event_location' => 'Campus Kiriri — FSI',
                'registration_url' => null,
                'seo_title' => 'Journée projets FSI',
                'seo_description' => 'Journée des projets ingénieurs.',
                'cover_image' => null,
                'created_by' => null,
                'updated_by' => null,
            ],
        ],
        'highlights' => [
            ['bi-building', 'Quatre départements', 'Génie civil, Architecture, Électromécanique, TIC.', 1],
            ['bi-geo-alt', 'Campus Kiriri', 'Formation sur le site historique de Kiriri à Bujumbura.', 2],
            ['bi-cpu', 'Ingénierie appliquée', 'Projets pratiques et stages en entreprise.', 3],
        ],
        'pages' => [
            'faculty' => [
                'title' => 'La Faculté',
                'content' => [
                    'banner_subtitle' => 'FSI — Sciences de l’ingénieur',
                    'banner_image' => 'assets/images/faculties/fsi/banner.jpg',
                    'dean' => [
                        'label' => 'Mot du doyen',
                        'title' => 'Construire et innover',
                        'photo' => '',
                        'name' => 'Dr-Ir Abraham Niyongere',
                        'role' => 'Doyen',
                        'specialty' => 'Sciences de l’ingénieur',
                        'signature' => 'Dr-Ir Abraham Niyongere',
                        'paragraphs' => [
                            'La FSI forme des ingénieurs capables de répondre aux défis d’infrastructures, d’énergie et de numérique du Burundi.',
                            'Sur le campus Kiriri, nos quatre départements allient théorie et pratique.',
                        ],
                    ],
                    'mission_label' => 'Mission et vision',
                    'mission_title' => 'Ingénierie pour le pays',
                    'mission' => ['icon' => 'bi-bullseye', 'title' => 'Mission', 'paragraphs' => ['Former des ingénieurs compétents et éthiques pour le développement national.']],
                    'vision' => ['icon' => 'bi-eye', 'title' => 'Vision', 'paragraphs' => ['Une faculté d’ingénierie de référence en Afrique des Grands Lacs.']],
                    'values' => [
                        ['icon' => 'bi-tools', 'title' => 'Pratique', 'description' => 'Projets et laboratoires au cœur de la formation.'],
                        ['icon' => 'bi-shield-check', 'title' => 'Qualité', 'description' => 'Standards techniques et sécurité.'],
                        ['icon' => 'bi-people', 'title' => 'Partenariats', 'description' => 'Liens avec le monde professionnel.'],
                    ],
                    'history' => [
                        'label' => 'Historique',
                        'title' => 'De la FSA/ITS à la FSI',
                        'text' => 'La FSI résulte de la fusion de la Faculté des Sciences Appliquées et de l’Institut Technique Supérieur dans le cadre de la réforme LMD.',
                    ],
                ],
                'seo_title' => 'La FSI | Université du Burundi',
                'seo_description' => 'Présentation de la FSI.',
            ],
            'formations' => [
                'title' => 'Formations',
                'content' => [
                    'banner_subtitle' => 'Génie civil, architecture, électromécanique, TIC',
                    'banner_image' => 'assets/images/faculties/fsi/banner.jpg',
                    'offer_label' => 'Offre académique',
                    'offer_title' => 'Programmes FSI',
                    'offer_text' => 'Filières d’ingénierie organisées par département.',
                    'cta_title' => 'Admissions',
                    'cta_text' => 'Contactez fsi-info@ub.edu.bi ou le (+257) 22 22 47 94.',
                    'cta_label' => 'Contacter la faculté',
                    'cta_url' => '/contact',
                ],
                'seo_title' => 'Formations — FSI',
                'seo_description' => 'Programmes de la FSI.',
            ],
            'research' => [
                'title' => 'Recherche',
                'content' => [
                    'banner_subtitle' => 'Recherche et projets techniques',
                    'banner_image' => 'assets/images/faculties/fsi/banner.jpg',
                    'labs_label' => 'Plateformes',
                    'labs_title' => 'Laboratoires et ateliers',
                    'labs_text' => 'Travaux pratiques et projets de recherche appliquée.',
                    'publications_label' => 'Publications',
                    'publications_title' => 'Mémoires et rapports',
                    'publications_text' => 'Travaux issus des départements de la FSI.',
                    'projects_label' => 'Projets',
                    'projects_title' => 'Projets structurants',
                ],
                'seo_title' => 'Recherche — FSI',
                'seo_description' => 'Recherche à la FSI.',
            ],
            'alumni' => [
                'title' => 'Alumni',
                'content' => [
                    'banner_subtitle' => 'Réseau des ingénieurs FSI',
                    'banner_image' => 'assets/images/faculties/fsi/banner.jpg',
                    'intro_label' => 'Communauté',
                    'intro_title' => 'Anciens de la FSI',
                    'intro_paragraphs' => ['Les diplômés travaillent dans le BTP, l’énergie, le numérique et l’urbanisme.'],
                    'profiles_label' => 'Profils',
                    'profiles_title' => 'Parcours alumni',
                    'profiles_text' => 'Exemples de trajectoires.',
                    'testimonials_label' => 'Témoignages',
                    'testimonials_title' => 'Ils témoignent',
                    'cta_title' => 'Rejoindre le réseau',
                    'cta_text' => 'Écrivez à fsi-info@ub.edu.bi.',
                    'cta_label' => 'Nous contacter',
                    'cta_url' => '/contact',
                ],
                'seo_title' => 'Alumni — FSI',
                'seo_description' => 'Alumni FSI.',
            ],
            'contact' => [
                'title' => 'Contact',
                'content' => [
                    'banner_subtitle' => 'FSI — Campus Kiriri, 164 Chaussée Prince Louis Rwagasore',
                    'banner_image' => 'assets/images/faculties/fsi/banner.jpg',
                    'contact_label' => 'Coordonnées',
                    'contact_title' => 'Contacter la FSI',
                    'form_title' => 'Envoyer un message',
                    'form_help' => 'Précisez le département (Génie civil, Architecture, Électromécanique, TIC).',
                    'map_url' => 'https://www.google.com/maps?q=-3.389031%2C29.375322%20(FSI%20%E2%80%94%20164%20Chauss%C3%A9e%20Prince%20Louis%20Rwagasore%2C%20Campus%20Kiriri)&hl=fr&z=17&output=embed',
                ],
                'seo_title' => 'Contact — FSI',
                'seo_description' => 'Contacter la FSI.',
            ],
        ],
        'dean_block' => 'Message du doyen Dr-Ir Abraham Niyongere : former des ingénieurs pour les infrastructures, l’énergie et le numérique du Burundi.',
    ],
];
